'''length=int(input())
breath=int(input())
area=length*breath
print(area)
#another wave
length,breath = input().split()
length=int(length)
breath =int(breath)
area=length*breath
print(area)'''
#assigment2name=input()
 #Your code goes here
name=input()
age=int(input())
print('The name of the preson is ',name,' and the age is ',age,'.',sep='')


























